const express = require('express');
const router = express.Router();

const LISTINGS = [
  { id:101, type:'land', title:'Former Industrial Site — Regeneration Opportunity', address:'Trafford Park, Manchester', postcode:'M17 1PJ', region:'North West', agent:'Savills', agentContact:'james.roberts@savills.com', agentPhone:'0161 244 7700', price:3750000, size:'4.2 acres', tenure:'Freehold', status:'For Sale', planning:'Outline Planning Granted — 280 residential units', planningStatus:'Approved', planningRef:'22/81234/OUT', lpa:'Trafford Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Brownfield', tags:['Brownfield','OPP','Strategic Land'], listed:'2 days ago', yield_pct:null, lot:'Development Site', owner:'Trafford Industrial Holdings Ltd', ownerType:'UK Company', ownerCo:'12345678', lastSale:'£2.1m (March 2019)', titleNumber:'GM123456', tenants:[], description:'A prime brownfield regeneration opportunity in Trafford Park. Outline planning for 280 residential units. Serviced site with all utilities to boundary.', epc:'N/A', lat:53.4651, lng:-2.3180 },
  { id:102, type:'land', title:'Prime Greenfield Development Land', address:'Wilmslow Road, Alderley Edge, Cheshire', postcode:'SK9 7QD', region:'North West', agent:'Knight Frank', agentContact:'p.harrison@knightfrank.com', agentPhone:'0161 833 1144', price:5200000, size:'8.1 acres', tenure:'Freehold', status:'For Sale', planning:'Allocated in Local Plan — Class C3 Residential', planningStatus:'Allocated', planningRef:'CE/23/0912M', lpa:'Cheshire East Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Allocated', tags:['Greenfield','Allocated','Consented'], listed:'5 days ago', yield_pct:null, lot:'Development Site', owner:'Alderley Land Partnership LLP', ownerType:'LLP', ownerCo:'OC456789', lastSale:'£1.8m (Jan 2017)', titleNumber:'CH789012', tenants:[], description:'Allocated residential land in one of Cheshire\'s most sought-after villages. Suitable for luxury detached housing.', epc:'N/A', lat:53.3000, lng:-2.1150 },
  { id:103, type:'land', title:'Waterfront Development Opportunity', address:'Leith Docks, Edinburgh', postcode:'EH6 7DX', region:'Scotland', agent:'Colliers', agentContact:'s.mackenzie@colliers.com', agentPhone:'0131 225 6612', price:8400000, size:'3.7 acres', tenure:'Freehold', status:'For Sale', planning:'Mixed-use consent — 180 BTR units + 12,000 sqft retail', planningStatus:'Full PP Granted', planningRef:'23/04521/FUL', lpa:'City of Edinburgh Council', floodZone:'Zone 2 (Medium Risk)', floodRisk:'Medium', highlight:'Consented', tags:['Waterfront','BTR','Mixed Use'], listed:'1 week ago', yield_pct:null, lot:'Development Site', owner:'Forth Waterfront Developments Ltd', ownerType:'UK Company', ownerCo:'SC123890', lastSale:'£5.2m (Aug 2020)', titleNumber:'MID456123', tenants:[], description:'Consented waterfront development site in Edinburgh\'s Leith district. Full planning for 180 BTR apartments and 12,000 sqft retail.', epc:'N/A', lat:55.9780, lng:-3.1730 },
  { id:201, type:'commercial', title:'Grade A Office — Multi-Let Investment', address:'Spinningfields, Manchester', postcode:'M3 3JE', region:'North West', agent:'CBRE', agentContact:'d.wilson@cbre.com', agentPhone:'0161 233 5400', price:18500000, size:'42,000 sqft', tenure:'Freehold', status:'For Sale', planning:'Class E (Commercial)', planningStatus:'Existing Use', planningRef:'N/A', lpa:'Manchester City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'7.2% NIY', tags:['Grade A','Multi-Let','BREEAM Exc'], listed:'1 day ago', yield_pct:7.2, lot:'Office Investment', owner:'Spinningfields Office LP', ownerType:'LP (Guernsey)', ownerCo:'N/A', lastSale:'£14.2m (Oct 2019)', titleNumber:'MAN234567', tenants:[{name:'Deloitte LLP',floor:'Floors 4-6',sqft:'14,200 sqft',leaseExp:'Dec 2028',rent:'£420,000/yr',rentReview:'5-yearly upward only'},{name:'DWF Law LLP',floor:'Floors 2-3',sqft:'9,400 sqft',leaseExp:'Mar 2027',rent:'£280,000/yr',rentReview:'5-yearly upward only'},{name:'Barclays Bank PLC',floor:'Ground + Floor 1',sqft:'8,200 sqft',leaseExp:'Jun 2031',rent:'£245,000/yr',rentReview:'5-yearly CPI-linked'}], description:'Landmark Grade A office in Manchester\'s premier business district. BREEAM Excellent. Multi-let to three strong covenants with WAULT of 5.8 years.', epc:'B (38)', lat:53.4808, lng:-2.2486 },
  { id:202, type:'commercial', title:'Last Mile Logistics Unit — New Build', address:'East Midlands Gateway, Castle Donington', postcode:'DE74 2TZ', region:'East Midlands', agent:'Savills', agentContact:'r.smith@savills.com', agentPhone:'0115 934 8000', price:9750000, size:'35,000 sqft', tenure:'Freehold', status:'For Sale', planning:'B8 Use Class', planningStatus:'Existing Use', planningRef:'N/A', lpa:'North West Leicestershire DC', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.1% NIY', tags:['Logistics','New Build','Single Let'], listed:'2 days ago', yield_pct:5.1, lot:'Industrial Investment', owner:'Gateway Logistics REIT plc', ownerType:'UK REIT', ownerCo:'09876543', lastSale:'New Build', titleNumber:'LE345678', tenants:[{name:'Amazon UK Services Ltd',floor:'Entire building',sqft:'35,000 sqft',leaseExp:'Dec 2033',rent:'£497,250/yr',rentReview:'Annual CPI-linked (collar 2%, cap 4%)'}], description:'Brand new Grade A logistics let to Amazon on 10-year lease with annual CPI-linked reviews. Direct M1 J24 access.', epc:'A (22)', lat:52.8280, lng:-1.3280 },
  { id:203, type:'commercial', title:'High Street Retail Parade — Fully Let', address:'Buchanan Street, Glasgow', postcode:'G1 3HL', region:'Scotland', agent:'Knight Frank', agentContact:'a.campbell@knightfrank.com', agentPhone:'0141 221 9585', price:4200000, size:'8,500 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 1 Retail', planningStatus:'Existing Use', planningRef:'N/A', lpa:'Glasgow City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'6.8% NIY', tags:['Retail','Fully Let','Prime Pitch'], listed:'3 days ago', yield_pct:6.8, lot:'Retail Investment', owner:'Scottish Retail Properties Ltd', ownerType:'UK Company', ownerCo:'SC234567', lastSale:'£3.1m (Feb 2018)', titleNumber:'GLA567890', tenants:[{name:'Superdry plc',floor:'Unit 1',sqft:'4,200 sqft',leaseExp:'Sep 2026',rent:'£155,000/yr',rentReview:'5-yearly OMV'},{name:'Caffè Nero Ltd',floor:'Unit 2',sqft:'2,100 sqft',leaseExp:'Mar 2029',rent:'£82,000/yr',rentReview:'5-yearly CPI'},{name:'O2 (UK) Ltd',floor:'Unit 3',sqft:'2,200 sqft',leaseExp:'Dec 2027',rent:'£48,000/yr',rentReview:'5-yearly OMV'}], description:'Prime retail investment on Scotland\'s most famous shopping street. Three units let to established national retailers.', epc:'C (54)', lat:55.8609, lng:-4.2512 },
  { id:301, type:'residential', title:'BTR Block — 64 Apartments, Stabilised', address:'Deansgate, Manchester', postcode:'M3 4LQ', region:'North West', agent:'Savills', agentContact:'h.jones@savills.com', agentPhone:'0161 244 7700', price:22000000, size:'64 units', tenure:'Freehold', status:'For Sale', planning:'Class C3 Residential', planningStatus:'Existing Use', planningRef:'N/A', lpa:'Manchester City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.4% NIY', tags:['BTR','Stabilised','City Centre'], listed:'3 days ago', yield_pct:5.4, lot:'BTR Investment', owner:'Deansgate Resi Holdings Ltd', ownerType:'UK Company', ownerCo:'11234567', lastSale:'£16.5m (Jan 2021)', titleNumber:'MAN890123', tenants:[{name:'Multiple AST Tenants',floor:'All 64 units',sqft:'42,800 sqft total',leaseExp:'Rolling ASTs',rent:'£1,188,000/yr gross',rentReview:'Annual market review'}], description:'Stabilised BTR block in prime Manchester. 97% occupancy. 1, 2 and 3-bed apartments with gym, concierge and rooftop terrace.', epc:'B (42)', lat:53.4794, lng:-2.2453 },
  { id:302, type:'residential', title:'HMO Portfolio — 8 Properties', address:'Headingley, Leeds', postcode:'LS6 1DP', region:'Yorkshire', agent:'Purplebricks Commercial', agentContact:'commercial@purplebricks.com', agentPhone:'0113 467 0890', price:3200000, size:'8 HMOs / 54 beds', tenure:'Freehold', status:'For Sale', planning:'Sui Generis HMO', planningStatus:'Existing Use', planningRef:'Various', lpa:'Leeds City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'9.1% NIY', tags:['HMO','Portfolio','Licensed'], listed:'4 days ago', yield_pct:9.1, lot:'HMO Portfolio', owner:'Headingley Property Group Ltd', ownerType:'UK Company', ownerCo:'08765432', lastSale:'Various (2015-2020)', titleNumber:'Various', tenants:[{name:'Student/Professional Tenants',floor:'54 beds across 8 properties',sqft:'N/A',leaseExp:'Rolling ASTs',rent:'£291,200/yr gross',rentReview:'Annual'}], description:'8 fully licensed HMOs in Leeds\'s most popular lettings area. All properties hold valid HMO licences. 100% occupied.', epc:'Various D-E', lat:53.8140, lng:-1.5680 },
  { id:401, type:'mixed', title:'Mixed-Use Freehold Block — Retail + 6 Flats', address:'Stoke Newington High Street, London', postcode:'N16 7PL', region:'London', agent:'Allsop', agentContact:'residential@allsop.co.uk', agentPhone:'020 7437 6977', price:2850000, size:'4,200 sqft', tenure:'Freehold', status:'For Sale', planning:'Class E + C3 Residential', planningStatus:'Existing Use', planningRef:'N/A', lpa:'London Borough of Hackney', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.2% NIY', tags:['Mixed Use','Freehold','London'], listed:'2 days ago', yield_pct:5.2, lot:'Mixed Use Investment', owner:'Stokey Properties Ltd', ownerType:'UK Company', ownerCo:'07654321', lastSale:'£1.9m (Nov 2016)', titleNumber:'LN678901', tenants:[{name:'Pret A Manger Ltd',floor:'Ground floor',sqft:'1,100 sqft',leaseExp:'Mar 2028',rent:'£52,000/yr',rentReview:'5-yearly OMV'},{name:'Residential x6',floor:'Floors 1-3',sqft:'3,100 sqft',leaseExp:'Rolling ASTs',rent:'£96,000/yr gross',rentReview:'Annual'}], description:'Classic London mixed-use freehold. Ground floor let to Pret A Manger. Six flats above on ASTs. Potential to extend leases.', epc:'C (68)', lat:51.5630, lng:-0.0730 },
  { id:402, type:'mixed', title:'Landmark Mixed-Use Development — Consented', address:'Granary Wharf, Leeds', postcode:'LS1 4BR', region:'Yorkshire', agent:'JLL', agentContact:'p.bradley@jll.com', agentPhone:'0113 244 6440', price:16500000, size:'1.4 acres', tenure:'Freehold', status:'For Sale', planning:'Full PP — 120 resi + 15,000 sqft commercial', planningStatus:'Full PP Granted', planningRef:'23/07821/FU', lpa:'Leeds City Council', floodZone:'Zone 2 (Medium Risk)', floodRisk:'Medium', highlight:'Full PP', tags:['Mixed Use','Consented','Waterfront'], listed:'3 days ago', yield_pct:null, lot:'Development Site', owner:'Granary Wharf Developments LLP', ownerType:'LLP', ownerCo:'OC789123', lastSale:'£9.8m (Jun 2021)', titleNumber:'WY234890', tenants:[], description:'Prime waterfront development with full planning for 120 residential units and 15,000 sqft commercial. Adjacent to Leeds station.', epc:'N/A', lat:53.7938, lng:-1.5490 },
  { id:403, type:'commercial', title:'Town Centre Office — Vacant Possession', address:'St Vincent Street, Glasgow', postcode:'G2 5TQ', region:'Scotland', agent:'Avison Young', agentContact:'glasgow@avisonyoung.com', agentPhone:'0141 248 8888', price:5800000, size:'24,500 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 4 Office / Conversion Potential', planningStatus:'Existing Use', planningRef:'N/A', lpa:'Glasgow City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Vacant — PD Right', tags:['Office','Vacant','Conversion Potential'], listed:'1 week ago', yield_pct:null, lot:'Office / Dev', owner:'St Vincent Street Properties Ltd', ownerType:'UK Company', ownerCo:'SC345678', lastSale:'£4.2m (Mar 2020)', titleNumber:'GLA890234', tenants:[], description:'Vacant city centre office with prior approval for 75-apartment residential conversion. Option to refurbish and re-let.', epc:'D (82)', lat:55.8630, lng:-4.2620 },
  { id:404, type:'land', title:'Prominent Town Centre Cleared Site', address:'High Street, Wolverhampton', postcode:'WV1 1TQ', region:'West Midlands', agent:'JLL', agentContact:'b.midlands@jll.com', agentPhone:'0121 232 7979', price:2100000, size:'0.9 acres', tenure:'Freehold', status:'For Sale', planning:'Full Planning — 45 apartments + ground floor commercial', planningStatus:'Full PP Granted', planningRef:'23/0234/FUL', lpa:'City of Wolverhampton Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Full PP', tags:['Brownfield','Full PP','Town Centre'], listed:'3 days ago', yield_pct:null, lot:'Development Site', owner:'Wolverhampton Land Co Ltd', ownerType:'UK Company', ownerCo:'06543210', lastSale:'£850k (Dec 2018)', titleNumber:'WM567890', tenants:[], description:'Cleared brownfield in Wolverhampton town centre with full planning for 45 apartments and 2,800 sqft commercial.', epc:'N/A', lat:52.5862, lng:-2.1292 },
];

const AGENTS = [...new Set(LISTINGS.map(l=>l.agent))].sort();
const REGIONS = [...new Set(LISTINGS.map(l=>l.region))].sort();

router.get('/', (req, res) => {
  let results = [...LISTINGS];
  const { type, region, agent, minPrice, maxPrice, minYield, q } = req.query;
  if (type && type !== 'all') results = results.filter(l => l.type === type);
  if (region) results = results.filter(l => l.region.toLowerCase().includes(region.toLowerCase()));
  if (agent) results = results.filter(l => l.agent.toLowerCase().includes(agent.toLowerCase()));
  if (minPrice) results = results.filter(l => l.price >= +minPrice);
  if (maxPrice) results = results.filter(l => l.price <= +maxPrice);
  if (minYield) results = results.filter(l => l.yield_pct && l.yield_pct >= +minYield);
  if (q) { const qL = q.toLowerCase(); results = results.filter(l => l.title.toLowerCase().includes(qL) || l.address.toLowerCase().includes(qL) || l.postcode.toLowerCase().includes(qL) || l.agent.toLowerCase().includes(qL) || l.tags.some(t=>t.toLowerCase().includes(qL)) || l.owner.toLowerCase().includes(qL)); }
  res.json({ listings: results, summary: { total: results.length, totalValue: results.reduce((s,l)=>s+l.price,0), byType: results.reduce((acc,l)=>{ acc[l.type]=(acc[l.type]||0)+1; return acc; },{}), agents: AGENTS, regions: REGIONS }});
});

router.get('/:id', (req, res) => {
  const l = LISTINGS.find(l => l.id === +req.params.id);
  if (!l) return res.status(404).json({ error: 'Not found' });
  res.json(l);
});

module.exports = router;
