const express = require('express');
const router = express.Router();

const LISTINGS = [
  // EDINBURGH
  { id:101, type:'land', title:'Prime New Town Development Site — 58 Apartments Consented', address:'India Street, Edinburgh New Town', postcode:'EH3 6HH', region:'Scotland', agent:'Knight Frank', agentContact:'edinburgh@knightfrank.com', agentPhone:'0131 222 9600', price:4200000, size:'0.4 acres', tenure:'Freehold', status:'For Sale', planning:'Full Planning Consent — 58 apartments + 3 commercial units (ref: 23/02841/FUL)', planningStatus:'Full PP Granted', planningRef:'23/02841/FUL', lpa:'City of Edinburgh Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Full PP', tags:['New Town','Consented','Residential'], listed:'3 days ago', yield_pct:null, lot:'Development Site', owner:'India Street Developments Ltd', ownerType:'UK Company', ownerCo:'SC123456', lastSale:'£2.8m (Apr 2021)', titleNumber:'MID123456', tenants:[], description:'Exceptional development opportunity in Edinburgh\'s prestigious New Town conservation area. Full planning consent for 58 high-spec apartments and 3 ground floor commercial units. Overlooking private gardens.', epc:'N/A', lat:55.9558, lng:-3.2055 },
  { id:102, type:'commercial', title:'Grade A Office — Haymarket, Multi-Let', address:'Morrison Street, Haymarket, Edinburgh', postcode:'EH3 8BJ', region:'Scotland', agent:'Savills', agentContact:'edinburgh@savills.com', agentPhone:'0131 247 3700', price:9800000, size:'24,500 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 4 Office', planningStatus:'Existing Use', planningRef:'N/A', lpa:'City of Edinburgh Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'7.1% NIY', tags:['Grade A','Multi-Let','Haymarket'], listed:'1 day ago', yield_pct:7.1, lot:'Office Investment', owner:'Haymarket Office Holdings LP', ownerType:'LP (Jersey)', ownerCo:'N/A', lastSale:'£7.4m (Nov 2019)', titleNumber:'MID234567', tenants:[{name:'Baillie Gifford & Co',floor:'Floors 3-4',sqft:'9,800 sqft',leaseExp:'Dec 2028',rent:'£294,000/yr',rentReview:'5-yearly upward only'},{name:'Brodies LLP',floor:'Floor 2',sqft:'7,200 sqft',leaseExp:'Jun 2027',rent:'£216,000/yr',rentReview:'5-yearly upward only'},{name:'Scottish Enterprise',floor:'Ground + Floor 1',sqft:'7,500 sqft',leaseExp:'Mar 2030',rent:'£186,000/yr',rentReview:'5-yearly CPI'}], description:'Modern Grade A office investment 3 minutes walk from Haymarket station. Multi-let to three strong Scottish covenants. WAULT 5.2 years. BREEAM Very Good.', epc:'B (41)', lat:55.9450, lng:-3.2190 },
  { id:103, type:'commercial', title:'Leith Waterfront Retail Parade — Fully Let', address:'Commercial Street, Leith, Edinburgh', postcode:'EH6 6JA', region:'Scotland', agent:'Colliers', agentContact:'edinburgh@colliers.com', agentPhone:'0131 225 6612', price:3100000, size:'6,200 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 1/2 Retail & Commercial', planningStatus:'Existing Use', planningRef:'N/A', lpa:'City of Edinburgh Council', floodZone:'Zone 2 (Medium Risk)', floodRisk:'Medium', highlight:'6.9% NIY', tags:['Retail','Leith','Fully Let'], listed:'5 days ago', yield_pct:6.9, lot:'Retail Investment', owner:'Leith Commercial Properties Ltd', ownerType:'UK Company', ownerCo:'SC345678', lastSale:'£2.1m (Aug 2018)', titleNumber:'MID345678', tenants:[{name:'Pret A Manger Ltd',floor:'Unit 1',sqft:'1,800 sqft',leaseExp:'Sep 2027',rent:'£72,000/yr',rentReview:'5-yearly OMV'},{name:'The Scotch Malt Whisky Society',floor:'Unit 2',sqft:'2,400 sqft',leaseExp:'Dec 2029',rent:'£84,000/yr',rentReview:'5-yearly CPI'},{name:'Gym Boutique Ltd',floor:'Unit 3',sqft:'2,000 sqft',leaseExp:'Mar 2026',rent:'£58,000/yr',rentReview:'5-yearly OMV'}], description:'Three-unit retail parade on vibrant Commercial Street in Leith\'s waterfront quarter. Fully let. Strong footfall from residential and tourism.', epc:'C (52)', lat:55.9756, lng:-3.1728 },
  { id:104, type:'land', title:'Waterfront BTR Site — 180 Units Consented', address:'Western Harbour, Leith, Edinburgh', postcode:'EH6 7DX', region:'Scotland', agent:'CBRE', agentContact:'edinburgh@cbre.com', agentPhone:'0131 469 7900', price:8400000, size:'3.7 acres', tenure:'Freehold', status:'For Sale', planning:'Full PP — 180 BTR + 12,000 sqft retail (ref: 23/04521/FUL)', planningStatus:'Full PP Granted', planningRef:'23/04521/FUL', lpa:'City of Edinburgh Council', floodZone:'Zone 2 (Medium Risk)', floodRisk:'Medium', highlight:'Consented BTR', tags:['BTR','Waterfront','Consented'], listed:'1 week ago', yield_pct:null, lot:'Development Site', owner:'Forth Waterfront Developments Ltd', ownerType:'UK Company', ownerCo:'SC123890', lastSale:'£5.2m (Aug 2020)', titleNumber:'MID456123', tenants:[], description:'Landmark waterfront BTR development with full planning for 180 apartments and 12,000 sqft retail. Adjacent to Ocean Terminal.', epc:'N/A', lat:55.9780, lng:-3.1730 },
  { id:105, type:'mixed', title:'Southside Mixed-Use Freehold — Retail + 8 Flats', address:'Clerk Street, Newington, Edinburgh', postcode:'EH8 9JG', region:'Scotland', agent:'JLL', agentContact:'edinburgh@jll.com', agentPhone:'0131 225 9292', price:2650000, size:'5,400 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 1 Retail (Ground) + Class 9 Residential (Upper)', planningStatus:'Existing Use', planningRef:'N/A', lpa:'City of Edinburgh Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.8% NIY', tags:['Mixed Use','Freehold','Newington'], listed:'2 days ago', yield_pct:5.8, lot:'Mixed Use Investment', owner:'Clerk Street Properties Ltd', ownerType:'UK Company', ownerCo:'SC456789', lastSale:'£1.75m (Feb 2016)', titleNumber:'MID567890', tenants:[{name:'Waterstones Booksellers Ltd',floor:'Ground floor retail',sqft:'2,200 sqft',leaseExp:'Jun 2028',rent:'£66,000/yr',rentReview:'5-yearly OMV'},{name:'Residential Tenants x8',floor:'Floors 1-3',sqft:'3,200 sqft total',leaseExp:'Rolling PATTs',rent:'£88,000/yr gross',rentReview:'Annual market'}], description:'Prime Southside freehold on Edinburgh\'s busiest student and local high street. Ground floor let to Waterstones. Eight furnished flats above with strong student demand.', epc:'D (68)', lat:55.9412, lng:-3.1854 },
  { id:106, type:'residential', title:'HMO Portfolio — 6 Properties, Marchmont & Bruntsfield', address:'Marchmont Road, Edinburgh', postcode:'EH9 1HH', region:'Scotland', agent:'Avison Young', agentContact:'edinburgh@avisonyoung.com', agentPhone:'0131 225 9292', price:4100000, size:'6 HMOs / 44 beds', tenure:'Freehold', status:'For Sale', planning:'Sui Generis HMO', planningStatus:'Existing Use', planningRef:'Various', lpa:'City of Edinburgh Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'8.4% NIY', tags:['HMO','Portfolio','Licensed'], listed:'4 days ago', yield_pct:8.4, lot:'HMO Portfolio', owner:'Marchmont Property Group Ltd', ownerType:'UK Company', ownerCo:'SC234567', lastSale:'Various (2016-2021)', titleNumber:'Various', tenants:[{name:'Student/Professional Tenants',floor:'44 beds across 6 properties',sqft:'N/A',leaseExp:'Rolling PATTs',rent:'£344,400/yr gross',rentReview:'Annual'}], description:'Portfolio of 6 licensed HMOs in Edinburgh\'s most sought-after student lettings catchment. All hold valid City of Edinburgh HMO licences. 100% occupancy historically.', epc:'Various D-E', lat:55.9378, lng:-3.1940 },
  { id:107, type:'commercial', title:'West End Office — B-Listed, Conversion Potential', address:'Melville Street, Edinburgh West End', postcode:'EH3 7PE', region:'Scotland', agent:'Carter Jonas', agentContact:'edinburgh@carterjonas.co.uk', agentPhone:'0131 226 6242', price:3800000, size:'11,200 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 4 Office — Prior Approval for 12 residential units', planningStatus:'Prior Approval Granted', planningRef:'23/00891/PAN', lpa:'City of Edinburgh Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Vacant — Conv. Potential', tags:['Office','Vacant','B-Listed'], listed:'6 days ago', yield_pct:null, lot:'Office / Dev Opportunity', owner:'Melville Street Estate Ltd', ownerType:'UK Company', ownerCo:'SC567890', lastSale:'£3.1m (Jan 2020)', titleNumber:'MID678901', tenants:[], description:'B-Listed Georgian townhouse office in Edinburgh\'s prestigious West End. Recently vacated. Prior approval for conversion to 12 high-spec apartments. Comparable residential values exceed £600/sqft.', epc:'E (102)', lat:55.9495, lng:-3.2150 },
  { id:108, type:'land', title:'Gorgie Regeneration Site — OPP for 95 Units', address:'Gorgie Road, Edinburgh', postcode:'EH11 2LA', region:'Scotland', agent:'Savills', agentContact:'edinburgh@savills.com', agentPhone:'0131 247 3700', price:2900000, size:'1.8 acres', tenure:'Freehold', status:'For Sale', planning:'Outline Planning — 95 residential units (ref: 22/05612/PPP)', planningStatus:'OPP Granted', planningRef:'22/05612/PPP', lpa:'City of Edinburgh Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'OPP Granted', tags:['Brownfield','OPP','Regeneration'], listed:'2 weeks ago', yield_pct:null, lot:'Development Site', owner:'Gorgie Land Holdings LLP', ownerType:'LLP', ownerCo:'SC789012', lastSale:'£1.4m (Nov 2019)', titleNumber:'MID789012', tenants:[], description:'Brownfield regeneration site in rapidly improving Gorgie/Dalry corridor. Outline planning for 95 residential units. Adjacent to new Crossrail stop.', epc:'N/A', lat:55.9363, lng:-3.2453 },
  // REST OF UK
  { id:201, type:'commercial', title:'Grade A Office — Spinningfields, Multi-Let', address:'Spinningfields, Manchester', postcode:'M3 3JE', region:'North West', agent:'CBRE', agentContact:'manchester@cbre.com', agentPhone:'0161 233 5400', price:18500000, size:'42,000 sqft', tenure:'Freehold', status:'For Sale', planning:'Class E (Commercial)', planningStatus:'Existing Use', planningRef:'N/A', lpa:'Manchester City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'7.2% NIY', tags:['Grade A','Multi-Let','BREEAM Exc'], listed:'1 day ago', yield_pct:7.2, lot:'Office Investment', owner:'Spinningfields Office LP', ownerType:'LP (Guernsey)', ownerCo:'N/A', lastSale:'£14.2m (Oct 2019)', titleNumber:'MAN234567', tenants:[{name:'Deloitte LLP',floor:'Floors 4-6',sqft:'14,200 sqft',leaseExp:'Dec 2028',rent:'£420,000/yr',rentReview:'5-yearly upward only'},{name:'DWF Law LLP',floor:'Floors 2-3',sqft:'9,400 sqft',leaseExp:'Mar 2027',rent:'£280,000/yr',rentReview:'5-yearly upward only'},{name:'Barclays Bank PLC',floor:'Ground + Floor 1',sqft:'8,200 sqft',leaseExp:'Jun 2031',rent:'£245,000/yr',rentReview:'5-yearly CPI'}], description:'Landmark Grade A office in Manchester\'s premier business district. BREEAM Excellent. Multi-let to three strong covenants. WAULT 5.8 years.', epc:'B (38)', lat:53.4808, lng:-2.2486 },
  { id:202, type:'commercial', title:'Last Mile Logistics — New Build, Amazon Let', address:'East Midlands Gateway, Castle Donington', postcode:'DE74 2TZ', region:'East Midlands', agent:'Savills', agentContact:'nottingham@savills.com', agentPhone:'0115 934 8000', price:9750000, size:'35,000 sqft', tenure:'Freehold', status:'For Sale', planning:'B8 Use Class', planningStatus:'Existing Use', planningRef:'N/A', lpa:'North West Leicestershire DC', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.1% NIY', tags:['Logistics','New Build','Single Let'], listed:'2 days ago', yield_pct:5.1, lot:'Industrial Investment', owner:'Gateway Logistics REIT plc', ownerType:'UK REIT', ownerCo:'09876543', lastSale:'New Build', titleNumber:'LE345678', tenants:[{name:'Amazon UK Services Ltd',floor:'Entire building',sqft:'35,000 sqft',leaseExp:'Dec 2033',rent:'£497,250/yr',rentReview:'Annual CPI (collar 2%, cap 4%)'}], description:'Brand new Grade A logistics let to Amazon on 10-year lease. Annual CPI reviews. Direct M1 J24 access.', epc:'A (22)', lat:52.8280, lng:-1.3280 },
  { id:203, type:'residential', title:'BTR Block — 64 Apartments, Stabilised', address:'Deansgate, Manchester', postcode:'M3 4LQ', region:'North West', agent:'Savills', agentContact:'manchester@savills.com', agentPhone:'0161 244 7700', price:22000000, size:'64 units', tenure:'Freehold', status:'For Sale', planning:'Class C3 Residential', planningStatus:'Existing Use', planningRef:'N/A', lpa:'Manchester City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.4% NIY', tags:['BTR','Stabilised','City Centre'], listed:'3 days ago', yield_pct:5.4, lot:'BTR Investment', owner:'Deansgate Resi Holdings Ltd', ownerType:'UK Company', ownerCo:'11234567', lastSale:'£16.5m (Jan 2021)', titleNumber:'MAN890123', tenants:[{name:'Multiple AST Tenants',floor:'All 64 units',sqft:'42,800 sqft',leaseExp:'Rolling ASTs',rent:'£1,188,000/yr gross',rentReview:'Annual market'}], description:'Stabilised BTR in prime Manchester. 97% occupancy. 1, 2 and 3-bed with gym, concierge and rooftop terrace. Managed by Grainger plc.', epc:'B (42)', lat:53.4794, lng:-2.2453 },
  { id:204, type:'land', title:'Consented Mixed-Use — Leeds South Bank', address:'Granary Wharf, Leeds', postcode:'LS1 4BR', region:'Yorkshire', agent:'JLL', agentContact:'leeds@jll.com', agentPhone:'0113 244 6440', price:16500000, size:'1.4 acres', tenure:'Freehold', status:'For Sale', planning:'Full PP — 120 resi + 15,000 sqft commercial (ref: 23/07821/FU)', planningStatus:'Full PP Granted', planningRef:'23/07821/FU', lpa:'Leeds City Council', floodZone:'Zone 2 (Medium Risk)', floodRisk:'Medium', highlight:'Full PP', tags:['Mixed Use','Consented','Waterfront'], listed:'3 days ago', yield_pct:null, lot:'Development Site', owner:'Granary Wharf Developments LLP', ownerType:'LLP', ownerCo:'OC789123', lastSale:'£9.8m (Jun 2021)', titleNumber:'WY234890', tenants:[], description:'Prime waterfront site with full planning for 120 resi units and 15,000 sqft commercial. Adjacent to Leeds station.', epc:'N/A', lat:53.7938, lng:-1.5490 },
  { id:205, type:'mixed', title:'Mixed-Use Freehold — London N16, Retail + 6 Flats', address:'Stoke Newington High Street, London', postcode:'N16 7PL', region:'London', agent:'Allsop', agentContact:'residential@allsop.co.uk', agentPhone:'020 7437 6977', price:2850000, size:'4,200 sqft', tenure:'Freehold', status:'For Sale', planning:'Class E + C3 Residential', planningStatus:'Existing Use', planningRef:'N/A', lpa:'London Borough of Hackney', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'5.2% NIY', tags:['Mixed Use','Freehold','London'], listed:'2 days ago', yield_pct:5.2, lot:'Mixed Use Investment', owner:'Stokey Properties Ltd', ownerType:'UK Company', ownerCo:'07654321', lastSale:'£1.9m (Nov 2016)', titleNumber:'LN678901', tenants:[{name:'Pret A Manger Ltd',floor:'Ground floor',sqft:'1,100 sqft',leaseExp:'Mar 2028',rent:'£52,000/yr',rentReview:'5-yearly OMV'},{name:'Residential x6',floor:'Floors 1-3',sqft:'3,100 sqft',leaseExp:'Rolling ASTs',rent:'£96,000/yr gross',rentReview:'Annual'}], description:'Classic London mixed-use freehold. Ground floor let to Pret A Manger. Six flats above on ASTs.', epc:'C (68)', lat:51.5630, lng:-0.0730 },
  { id:206, type:'commercial', title:'Glasgow City Centre Office — Vacant, Conv. Potential', address:'St Vincent Street, Glasgow', postcode:'G2 5TQ', region:'Scotland', agent:'Avison Young', agentContact:'glasgow@avisonyoung.com', agentPhone:'0141 248 8888', price:5800000, size:'24,500 sqft', tenure:'Freehold', status:'For Sale', planning:'Class 4 Office / Conversion PA Granted', planningStatus:'Prior Approval Granted', planningRef:'23/00891/PAN', lpa:'Glasgow City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Vacant — Conv. Potential', tags:['Office','Vacant','Conversion'], listed:'1 week ago', yield_pct:null, lot:'Office / Dev', owner:'St Vincent Street Properties Ltd', ownerType:'UK Company', ownerCo:'SC345678', lastSale:'£4.2m (Mar 2020)', titleNumber:'GLA890234', tenants:[], description:'Vacant city centre office with prior approval for 75-apartment residential conversion. Strong PRS and PBSA operator interest.', epc:'D (82)', lat:55.8630, lng:-4.2620 },
  { id:207, type:'land', title:'Birmingham City Centre Site — 45 Apts Full PP', address:'High Street, Birmingham City Centre', postcode:'B4 7SL', region:'West Midlands', agent:'JLL', agentContact:'birmingham@jll.com', agentPhone:'0121 232 7979', price:3400000, size:'0.9 acres', tenure:'Freehold', status:'For Sale', planning:'Full PP — 45 apartments + ground floor commercial', planningStatus:'Full PP Granted', planningRef:'23/04521/FUL', lpa:'Birmingham City Council', floodZone:'Zone 1 (Low Risk)', floodRisk:'Low', highlight:'Full PP', tags:['Brownfield','Full PP','City Centre'], listed:'5 days ago', yield_pct:null, lot:'Development Site', owner:'Birmingham Land Co Ltd', ownerType:'UK Company', ownerCo:'06543210', lastSale:'£1.2m (Dec 2019)', titleNumber:'WM567890', tenants:[], description:'Cleared brownfield in Birmingham city centre with full planning for 45 apartments and 2,800 sqft commercial. HS2 proximity.', epc:'N/A', lat:52.4796, lng:-1.8985 },
];

const AGENTS = [...new Set(LISTINGS.map(l=>l.agent))].sort();
const REGIONS = [...new Set(LISTINGS.map(l=>l.region))].sort();

router.get('/', (req, res) => {
  let results = [...LISTINGS];
  const { type, region, agent, minPrice, maxPrice, minYield, q } = req.query;
  if (type && type !== 'all') results = results.filter(l => l.type === type);
  if (region) results = results.filter(l => l.region.toLowerCase().includes(region.toLowerCase()));
  if (agent) results = results.filter(l => l.agent.toLowerCase().includes(agent.toLowerCase()));
  if (minPrice) results = results.filter(l => l.price >= +minPrice);
  if (maxPrice) results = results.filter(l => l.price <= +maxPrice);
  if (minYield) results = results.filter(l => l.yield_pct && l.yield_pct >= +minYield);
  if (q) { const qL = q.toLowerCase(); results = results.filter(l => l.title.toLowerCase().includes(qL) || l.address.toLowerCase().includes(qL) || l.postcode.toLowerCase().includes(qL) || l.agent.toLowerCase().includes(qL) || l.tags.some(t=>t.toLowerCase().includes(qL)) || l.owner.toLowerCase().includes(qL)); }
  res.json({ listings: results, summary: { total: results.length, totalValue: results.reduce((s,l)=>s+l.price,0), byType: results.reduce((acc,l)=>{ acc[l.type]=(acc[l.type]||0)+1; return acc; },{}), agents: AGENTS, regions: REGIONS }});
});

router.get('/:id', (req, res) => {
  const l = LISTINGS.find(l => l.id === +req.params.id);
  if (!l) return res.status(404).json({ error: 'Not found' });
  res.json(l);
});

module.exports = router;
